// <auto-generated />
using System;
using LoyaltySystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltySystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304082026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.Account", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Số điện thoại - là Primary Key");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Mật khẩu đã hash");

                    b.HasKey("PhoneNumber");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.MonthlyPoints", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasComment("ID khách hàng - FK đến bảng Users");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasComment("Tháng (1-12)");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasComment("Năm (VD: 2024)");

                    b.Property<int>("MonthlyTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Tổng điểm tích lũy trong tháng");

                    b.HasKey("CustomerId", "Month", "Year");

                    b.ToTable("MonthlyPoints", (string)null);
                });

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID đơn hàng - Identity (auto-increment)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasComment("ID khách hàng - FK đến bảng Users");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Giá trị đơn hàng (VNĐ)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasComment("ID nhân viên tạo đơn - FK đến bảng Users");

                    b.Property<DateTime>("TimeCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Thời gian tạo đơn hàng");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Order_CustomerId");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("IX_Order_StaffId");

                    b.HasIndex("TimeCreate")
                        .HasDatabaseName("IX_Order_TimeCreate");

                    b.HasIndex("CustomerId", "TimeCreate")
                        .HasDatabaseName("IX_Order_Customer_Time");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID người dùng - Identity (auto-increment)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Số điện thoại - Unique, FK đến Account");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer")
                        .HasComment("Vai trò: Admin, Staff, Customer");

                    b.Property<int>("TotalPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Tổng điểm tích lũy trọn đời (dùng cho ranking)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Tên người dùng");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.Account", b =>
                {
                    b.HasOne("LoyaltySystem.Domain.Entities.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("LoyaltySystem.Domain.Entities.Account", "PhoneNumber")
                        .HasPrincipalKey("LoyaltySystem.Domain.Entities.User", "PhoneNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.MonthlyPoints", b =>
                {
                    b.HasOne("LoyaltySystem.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.Order", b =>
                {
                    b.HasOne("LoyaltySystem.Domain.Entities.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LoyaltySystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
